### PR TITLE
Fix static property inheritance (fixes #7)

### LINKED ISSUE #7: Backbone static property inheritance is broken.
After wrapping model in UniqueModel it's static properties ar gone.

Heres a test case showing it.

https://github.com/janispauls/backbone.uniquemodel/commit/9acfd0764e8665a6600b86fc3978bab1da534911

### PR DESCRIPTION
**Pull request by benvinegar**

### CODE REVIEW

File: backbone.uniquemodel.js [hunk 1]
```diff
@@ -104,6 +104,12 @@
     var modelConstructor = function (attrs, options) {
       return self.get(attrs, options);
     };
+
+    // Extend Model's static properties onto new
+    _.extend(modelConstructor, Model);
+
+    // NOTE: currently possible for Backbone.Events functions to collide with
+    //       Model static properties e.g. Model.on vs Backbone.Events.on
     _.extend(modelConstructor, Backbone.Events);
```
Comment (BYK) [inline backbone.uniquemodel.js:113]: You can actually do

```
_.extend(modelConstructor, Model, BackboneEvents);
```

That said I don't think it improves performance and makes commenting harder so I'll pass.

**Comment by BYK** [comment]
Nice.
